{
 "title": "Spark Applications Dashboard",
 "description": "Spark Executors and Driver Level Metrics with filtering by service",
 "tags": [ "spark" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "K8s Namespace", "query": "spark-operator" },
   { "name": "app_name", "label": "Application Name", "query": "shk-app" }
  ]
 },
 "panels": [
  { "title": "Cluster Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Drivers Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_labels{label_spark_role=\"driver\"})"
    }
   ]
  },
  {
   "title": "CPUs Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"spark-operator\", container=~\"spark-kubernetes-driver\"})",
     "legendFormat": "CPUs Used by Driver"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"spark-operator\", container=~\"spark-kubernetes-executor\"})",
     "legendFormat": "CPUs Used by Executor"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"spark-operator\", container=~\"spark-kubernetes-driver|spark-kubernetes-executor\"})\n",
     "legendFormat": "Total CPUs Used"
    }
   ]
  },
  {
   "title": "Mem Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"spark-operator\", container=\"spark-kubernetes-driver\"})",
     "legendFormat": "Mem Used by Driver"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"spark-operator\", container=\"spark-kubernetes-executor\"})",
     "legendFormat": "Mem Used by Executors"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"spark-operator\", container=~\"spark-kubernetes-driver|spark-kubernetes-executor\"})",
     "legendFormat": "Total Mem Used"
    }
   ]
  },
  {
   "title": "Executors Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_labels{label_spark_role=\"executor\"})"
    }
   ]
  },
  { "title": "Execution Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Driver Heap (max/used)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "spark_driver_jvm_total_max_type_gauges{app_namespace=\"$namespace\", app_id=~\"$app_name\"}",
     "legendFormat": "Heap max ({{app_id}})"
    },
    {
     "expr": "spark_driver_jvm_total_used_type_gauges{app_namespace=\"$namespace\", app_id=~\"$app_name\"}",
     "legendFormat": "Heap used ({{app_id}})"
    }
   ]
  },
  {
   "title": "Executor Heap (max/used)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "spark_executor_jvm_total_max_type_gauges{app_namespace=\"$namespace\", app_id=~\"$app_name\"}",
     "legendFormat": "Heap max ({{app_id}})"
    },
    {
     "expr": "spark_executor_jvm_total_used_type_gauges{app_namespace=\"$namespace\", app_id=~\"$app_name\"}",
     "legendFormat": "Heap used ({{app_id}})"
    }
   ]
  },
  {
   "title": "BlockManager (on-heap memory)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_driver_blockmanager_memory_maxonheapmem_mb_type_gauges{app_namespace=\"$namespace\",app_id=~\"$app_name\"}",
     "legendFormat": "Max On-Heap Memory  ({{app_id}})"
    },
    {
     "expr": "spark_driver_blockmanager_memory_onheapmemused_mb_type_gauges{app_namespace=\"$namespace\",app_id=~\"$app_name\"}",
     "legendFormat": "On-Heap Memory Used  ({{app_id}})"
    }
   ]
  },
  {
   "title": "BlockManager (off-heap memory)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_driver_blockmanager_memory_maxoffheapmem_mb_type_gauges{app_namespace=\"$namespace\", app_id=~\"$app_name\"}",
     "legendFormat": "Max Off-Heap Memory ({{app_id}})"
    },
    {
     "expr": "spark_driver_blockmanager_memory_offheapmemused_mb_type_gauges{app_namespace=\"$namespace\", app_id=~\"$app_name\"}",
     "legendFormat": "Off-Heap Memory Used ({{app_id}})"
    }
   ]
  },
  {
   "title": "BlockManager (disk)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_driver_blockmanager_disk_diskspaceused_mb_type_gauges{app_namespace=\"$namespace\", app_id=~\"$app_name\"}",
     "legendFormat": "Disk Space Used  ({{app_id}})"
    }
   ]
  },
  { "title": "DAG Scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_driver_dagscheduler_job_alljobs_type_gauges{app_namespace=\"$namespace\", app_id=~\"$app_name\"}",
     "legendFormat": "All Jobs ({{app_id}})"
    },
    {
     "expr": "spark_driver_dagscheduler_job_activejobs_type_gauges{app_namespace=\"$namespace\", app_id=~\"$app_name\"}",
     "legendFormat": "Active Jobs ({{app_id}})"
    }
   ]
  },
  {
   "title": "Stages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_driver_dagscheduler_stage_runningstages_type_gauges{namespace=\"$namespace\", app_id=~\"$app_name\"}",
     "legendFormat": "Running Stages ({{app_id}})"
    },
    {
     "expr": "spark_driver_dagscheduler_stage_waitingstages_type_gauges{namespace=\"$namespace\", app_id=~\"$app_name\"}",
     "legendFormat": "Waiting Stages  ({{app_id}})"
    },
    {
     "expr": "spark_driver_dagscheduler_stage_failedstages{namespace=\"$namespace\", app_id=~\"$app_name\"}",
     "legendFormat": "Failed Stages ({{app_id}})"
    }
   ]
  }
 ]
}